[versions]
androidGradlePlugin = "8.5.2"
kotlin = "2.0.20"
androidxCoreKtx = "1.13.1"
androidxAppcompat = "1.7.0"
material = "1.12.0"
androidxActivity = "1.9.2"
androidxConstraintlayout = "2.1.4"
sceneform = "1.15.0" # Googleâ€™s Sceneform version
arcore = "1.44.0"
junit = "4.13.2"
androidxJunit = "1.2.1"
androidxEspressoCore = "3.6.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
sceneform-ux = { module = "com.google.ar.sceneform.ux:sceneform-ux", version.ref = "sceneform" }
arcore = { module = "com.google.ar:core", version.ref = "arcore" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }